import Foundation

struct TaskState: Codable {
    let repo: String
    let branch: String
    let slug: String
    let worktreePath: String
    let simulatorName: String
    var simulatorUDID: String
    let derivedDataPath: String
    let scheme: String?
    let workspace: String?
    let project: String?
    let package: String?
    let createdAt: Date

    // Stacked PR support
    let parentBranch: String?
    let parentSlug: String?

    /// Generate a Copilot instructions file that auto-configures XcodeBuildMCP session defaults.
    func copilotInstructionsContent() -> String {
        var lines = [
            "---",
            "applyTo: \"**\"",
            "---",
            "",
            "<!-- Auto-generated by xwt — do not edit -->",
            "",
            "## XcodeBuildMCP Session Setup",
            "",
            "At the start of every session, before any build, run, or test action,",
            "configure XcodeBuildMCP session defaults by calling `session_set_defaults`",
            "with the following values. Do **not** set `persist: true`.",
            "",
            "- simulatorName: \(simulatorName)",
            "- simulatorId: \(simulatorUDID)",
            "- derivedDataPath: \(derivedDataPath)",
        ]
        if let workspace { lines.append("- workspacePath: \(workspace)") }
        if let project { lines.append("- projectPath: \(project)") }
        if let scheme { lines.append("- scheme: \(scheme)") }
        if package != nil {
            lines.append("")
            lines.append(
                "This is a Swift Package (Package.swift). Do not set workspacePath or projectPath; "
                + "XcodeBuildMCP will discover the package from the worktree directory."
            )
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Generate a Claude Code instructions block that auto-configures XcodeBuildMCP session defaults.
    /// Wrapped in markers so it can be inserted/replaced in an existing CLAUDE.local.md.
    func claudeCodeInstructionsContent() -> String {
        var lines = [
            "<!-- xwt:start -->",
            "<!-- Auto-generated by xwt — do not edit this block -->",
            "",
            "## XcodeBuildMCP Session Setup",
            "",
            "At the start of every session, before any build, run, or test action,",
            "configure XcodeBuildMCP session defaults by calling `session_set_defaults`",
            "with the following values. Do **not** set `persist: true`.",
            "",
            "- simulatorName: \(simulatorName)",
            "- simulatorId: \(simulatorUDID)",
            "- derivedDataPath: \(derivedDataPath)",
        ]
        if let workspace { lines.append("- workspacePath: \(workspace)") }
        if let project { lines.append("- projectPath: \(project)") }
        if let scheme { lines.append("- scheme: \(scheme)") }
        if package != nil {
            lines.append("")
            lines.append(
                "This is a Swift Package (Package.swift). Do not set workspacePath or projectPath; "
                + "XcodeBuildMCP will discover the package from the worktree directory."
            )
        }
        lines.append("")
        lines.append("<!-- xwt:end -->")
        return lines.joined(separator: "\n")
    }
}
