import Foundation

struct TaskState: Codable {
    let repo: String
    let branch: String
    let slug: String
    let worktreePath: String
    let simulatorName: String
    var simulatorUDID: String
    let derivedDataPath: String
    let scheme: String?
    let workspace: String?
    let project: String?
    let package: String?
    let createdAt: Date

    // Stacked PR support
    let parentBranch: String?
    let parentSlug: String?

    /// Generate a Copilot instructions file for the task's native Xcode MCP session.
    func copilotInstructionsContent() -> String {
        var lines = [
            "---",
            "applyTo: \"**\"",
            "---",
            "",
            "<!-- Auto-generated by xwt — do not edit -->",
            "",
        ]
        lines.append(contentsOf: xcodeMCPInstructions())
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Generate a Claude Code instructions block for the task's native Xcode MCP session.
    /// Wrapped in markers so it can be inserted/replaced in an existing CLAUDE.local.md.
    func claudeCodeInstructionsContent() -> String {
        var lines = [
            "<!-- xwt:start -->",
            "<!-- Auto-generated by xwt — do not edit this block -->",
            "",
        ]
        lines.append(contentsOf: xcodeMCPInstructions())
        lines.append("")
        lines.append("<!-- xwt:end -->")
        return lines.joined(separator: "\n")
    }

    private func xcodeMCPInstructions() -> [String] {
        var lines = [
            "## Xcode MCP Session Setup",
            "",
            "Use the native Xcode MCP server for all Xcode operations in this worktree.",
            "Do not use XcodeBuildMCP.",
            "",
        ]

        if let containerPath {
            lines += [
                "At the start of every session, before any build, run, test, preview, or simulator action,",
                "open the project container with `XcodeOpenWorkspace` and use its returned workspace",
                "identifier for all later Xcode MCP calls.",
                "",
                "- containerPath: \(containerPath)",
            ]
        }

        lines += [
            "- simulatorName: \(simulatorName)",
            "- simulatorId: \(simulatorUDID)",
            "- derivedDataPath: \(derivedDataPath)",
        ]
        if let scheme { lines.append("- scheme: \(scheme)") }

        lines += [
            "",
            "Always target the assigned simulator by its UDID so parallel worktrees remain isolated.",
            "Use the DerivedData path above whenever an Xcode MCP tool accepts a custom path.",
            "Use `xwt run \(branch)` to build, install, and launch the app.",
            "Do not use Xcode `RunProject` because it opens a compact Device Hub window.",
            "Do not open Simulator.app. View the assigned simulator in the existing full Device Hub window.",
        ]

        return lines
    }

    private var containerPath: String? {
        let relativePath = workspace ?? project ?? package
        guard let relativePath else { return nil }
        if relativePath.hasPrefix("/") { return relativePath }
        return URL(fileURLWithPath: worktreePath)
            .appendingPathComponent(relativePath)
            .standardizedFileURL
            .path
    }
}
