import ArgumentParser
import Foundation

struct ShellInit: ParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "shell-init",
        abstract: "Print a shell function that wraps xwt with `cd` and auto-cd-on-start.",
        discussion: """
        Add this to your shell's rc file:

          zsh   (~/.zshrc):                       eval "$(xwt shell-init zsh)"
          bash  (~/.bash_profile or ~/.bashrc):   eval "$(xwt shell-init bash)"
          fish  (~/.config/fish/config.fish):     xwt shell-init fish | source

        After installation:
          - `xwt cd <branch>` jumps to the worktree.
          - `xwt start <branch>` automatically cds into the new worktree.
            Set XWT_NO_CD=1 (in your environment) to opt out of auto-cd.
        """
    )

    @Argument(help: "Target shell: zsh, bash, or fish.")
    var shell: String

    func run() throws {
        switch shell.lowercased() {
        case "zsh", "bash":
            Terminal.out(Self.posixFunction)
        case "fish":
            Terminal.out(Self.fishFunction)
        default:
            Terminal.errorLine("unsupported shell '\(shell)' — supported: zsh, bash, fish")
            throw ExitCode.failure
        }
    }

    // MARK: - Wrapper sources
    //
    // The wrappers intercept `xwt cd <branch>` and `xwt start <branch>` and
    // delegate to the real binary via `command xwt …`. For `xwt start`, the
    // wrapper reads `~/.xwt/last-task-path` (written by `xwt start` after
    // success) to know where to auto-cd. This avoids fragile argv-parsing
    // when the user puts options between `start` and the branch name.

    private static let posixFunction = #"""
# xwt shell integration — generated by `xwt shell-init`.
# Provides `xwt cd <branch>` (jump to worktree) and auto-cd after `xwt start`.
# Set XWT_NO_CD=1 to disable auto-cd after `xwt start`.
xwt() {
    if [ "$1" = "cd" ]; then
        shift
        local _xwt_path
        _xwt_path=$(command xwt path "$@") || return $?
        cd "$_xwt_path"
    elif [ "$1" = "start" ] && [ -z "$XWT_NO_CD" ]; then
        command xwt "$@"
        local _xwt_status
        _xwt_status=$?
        if [ "$_xwt_status" -eq 0 ] && [ -f "$HOME/.xwt/last-task-path" ]; then
            local _xwt_path
            _xwt_path=$(cat "$HOME/.xwt/last-task-path" 2>/dev/null)
            if [ -n "$_xwt_path" ] && [ -d "$_xwt_path" ]; then
                cd "$_xwt_path"
            fi
        fi
        return $_xwt_status
    else
        command xwt "$@"
    fi
}
"""#

    private static let fishFunction = #"""
# xwt shell integration — generated by `xwt shell-init`.
# Provides `xwt cd <branch>` (jump to worktree) and auto-cd after `xwt start`.
# Set XWT_NO_CD=1 to disable auto-cd after `xwt start`.
function xwt
    if test (count $argv) -gt 0; and test $argv[1] = "cd"
        set -l _xwt_args $argv[2..-1]
        set -l _xwt_path (command xwt path $_xwt_args)
        or return $status
        cd $_xwt_path
    else if test (count $argv) -gt 0; and test $argv[1] = "start"; and not set -q XWT_NO_CD
        command xwt $argv
        set -l _xwt_status $status
        if test $_xwt_status -eq 0; and test -f "$HOME/.xwt/last-task-path"
            set -l _xwt_path (cat "$HOME/.xwt/last-task-path" 2>/dev/null)
            if test -n "$_xwt_path"; and test -d "$_xwt_path"
                cd $_xwt_path
            end
        end
        return $_xwt_status
    else
        command xwt $argv
    end
end
"""#
}
