import Foundation

struct TaskState: Codable {
    let repo: String
    let branch: String
    let slug: String
    let worktreePath: String
    let simulatorName: String
    var simulatorUDID: String
    let derivedDataPath: String
    let scheme: String?
    let workspace: String?
    let project: String?
    let createdAt: Date

    func simiContextContent() -> String {
        var lines = [
            "# Auto-generated by simi — do not edit",
            "export SIMI_BRANCH=\"\(branch)\"",
            "export SIMI_SLUG=\"\(slug)\"",
            "export SIMI_WORKTREE=\"\(worktreePath)\"",
            "export SIMI_SIMULATOR_NAME=\"\(simulatorName)\"",
            "export SIMI_SIMULATOR_UDID=\"\(simulatorUDID)\"",
            "export SIMI_DERIVED_DATA=\"\(derivedDataPath)\"",
        ]
        if let scheme { lines.append("export SIMI_SCHEME=\"\(scheme)\"") }
        if let workspace { lines.append("export SIMI_WORKSPACE=\"\(workspace)\"") }
        if let project { lines.append("export SIMI_PROJECT=\"\(project)\"") }
        lines.append("") // trailing newline
        return lines.joined(separator: "\n")
    }


}
