import Foundation

struct TaskState: Codable {
    let repo: String
    let branch: String
    let slug: String
    let worktreePath: String
    let simulatorName: String
    var simulatorUDID: String
    let derivedDataPath: String
    let scheme: String?
    let workspace: String?
    let project: String?
    let createdAt: Date

    func simiContextContent() -> String {
        var lines = [
            "# Auto-generated by simi — do not edit",
            "export SIMI_BRANCH=\(shellEscape(branch))",
            "export SIMI_SLUG=\(shellEscape(slug))",
            "export SIMI_WORKTREE=\(shellEscape(worktreePath))",
            "export SIMI_SIMULATOR_NAME=\(shellEscape(simulatorName))",
            "export SIMI_SIMULATOR_UDID=\(shellEscape(simulatorUDID))",
            "export SIMI_DERIVED_DATA=\(shellEscape(derivedDataPath))",
        ]
        if let scheme { lines.append("export SIMI_SCHEME=\(shellEscape(scheme))") }
        if let workspace { lines.append("export SIMI_WORKSPACE=\(shellEscape(workspace))") }
        if let project { lines.append("export SIMI_PROJECT=\(shellEscape(project))") }
        lines.append("") // trailing newline
        return lines.joined(separator: "\n")
    }

    /// Escape a value for safe use in a single-quoted shell string.
    /// Single-quoted strings prevent expansion of $, `, and other metacharacters.
    private func shellEscape(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
