import Foundation

struct TaskState: Codable {
    let repo: String
    let branch: String
    let slug: String
    let worktreePath: String
    let simulatorName: String
    var simulatorUDID: String
    let derivedDataPath: String
    let scheme: String?
    let workspace: String?
    let project: String?
    let createdAt: Date

    /// Generate a Copilot instructions file that auto-configures XcodeBuildMCP session defaults.
    func copilotInstructionsContent() -> String {
        var lines = [
            "---",
            "applyTo: \"**\"",
            "---",
            "",
            "<!-- Auto-generated by simi — do not edit -->",
            "",
            "## XcodeBuildMCP Session Setup",
            "",
            "At the start of every session, before any build, run, or test action,",
            "configure XcodeBuildMCP session defaults by calling `session_set_defaults`",
            "with the following values. Do **not** set `persist: true`.",
            "",
            "- simulatorName: \(simulatorName)",
            "- simulatorId: \(simulatorUDID)",
            "- derivedDataPath: \(derivedDataPath)",
        ]
        if let workspace { lines.append("- workspacePath: \(workspace)") }
        if let project { lines.append("- projectPath: \(project)") }
        if let scheme { lines.append("- scheme: \(scheme)") }
        lines.append("")
        return lines.joined(separator: "\n")
    }
}
